version: "3.1"

services:
  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: deno-blog-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "deno-blog-database"
    ports:
      - "3306:3306"
